services:
  - type: web
    name: thumblify-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
